---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gitea
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - image: postgres:alpine
        name: postgres
        env:
        - name: POSTGRES_USER
          value: gitea
        - name: POSTGRES_PASSWORD
          value: gitea
        volumeMounts:
          - name: postgres-data
            mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: pvc-postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitea
  labels:
    name: postgres
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea
  template:
    metadata:
      labels:
        name: gitea
    spec:
      containers:
      - image: kunde21/gitea-arm:arm-v1.7.2
        name: gitea
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        resources:
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 3000
        - containerPort: 22
        volumeMounts:
          - name: gitea-data
            mountPath: "/data"
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: pvc-gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: gitea
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea-ingress
  namespace: gitea
spec:
  rules:
  - host: git.servidor.local
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 3000