#cloud-config
hostname: servidor-worker
manage_etc_hosts: true

users:
  - name: ops
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    plain_text_passwd: felizcumpledocker
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }
    groups: sudo

package_update: true
package_upgrade: false

packages:
  - ntp
  - nfs-common

locale: "en_US.UTF-8"

timezone: "America/La_Paz"

runcmd:
  - systemctl disable docker
  - systemctl stop docker
  - sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - echo "Port 4444" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - curl -sfL https://get.k3s.io | K3S_URL=https://localhost:6443 K3S_CLUSTER_SECRET=felizcumpledocker sh -
  - systemctl enable k3s-agent